name: MATLAB Build

# Controls when the action will run. 
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]
  workflow_dispatch:

jobs:
  test:
    strategy: 
      fail-fast: false
      matrix:
        MATLABVersion: [R2023a,R2023b]
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.MATLABVersion }}

      # Runs a set of commands using the runners shell
      - name: Run all tests
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("SoftwareTests"); TestModule("ModuleName","fluid-mechanics.prj","ReportSubdirectory","${{ matrix.MATLABVersion }}");

      # Save the contents of the report directory from each release into a single artifact.  Since each release makes their own directory, they all update the same artifact.
      - name: Save Report Directory
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: report
          path: report

      # Generate the JSON for the releases tested badge
      - name: Generate tested with badge
        uses: matlab-actions/run-command@v1
        with:
          command: addpath("SoftwareTests"),BadgesforModule()     

      # Commit the JSON for the MATLAB releases badge 
      - name: commit changed files
        continue-on-error: true
        run: |
          git config user.name "${{ github.workflow }} by ${{ github.actor }}"
          git config user.email "<>"
          git commit Images/tested_with.json -m "Update CI badges ${{  github.ref_name }}"
          git fetch
          git push
